version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: ecommerce-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: ecommerce
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: ecommerce-backend
    ports:
      - "5000:5000"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root123
      DB_NAME: ecommerce
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    container_name: ecommerce-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mysql_data: